CREATE TABLE IF NOT EXISTS `bot_log` (
	`id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	`username` VARCHAR(255) NOT NULL,
	`message` VARCHAR(255) NOT NULL,
	`channel` VARCHAR(255) NOT NULL,
	`time` TIMESTAMP NOT NULL
);